Additions
TheTedder/leaderboard-admin pull request #1
Opened 2024-12-10 14:44 UTC by zysim

1. Autofocuses the email input in the Login Page
2. Makes confirmation prompts (to delete/restore a board) be in modals
3. Error handling UI for those modals

2024-12-10 14:46 UTC, zysim commented
On load error:
![image](https://github.com/user-attachments/assets/1470a865-80c1-4687-9336-2bfa5ec532be)

On deletion + error (modal background actually blurs; screenshots don't show it):
![image](https://github.com/user-attachments/assets/3d984281-b041-4b37-801c-79e1acacfdef)
![image](https://github.com/user-attachments/assets/d28ffe3b-fdaa-4942-9bd3-b8410f154660)

2024-12-15 19:08 UTC, TheTedder requested changes
Use kebab case for CSS classes. It's the standard for some reason.

2024-12-15 19:08 UTC, TheTedder commented on src/components/Leaderboard.vue
> +			updateError.value = 'Failed to delete: ' + (error as Response).status.toString(10)
You can use the `useApi` composable here for some nicer typing if you want to.

2024-12-15 19:08 UTC, TheTedder commented on src/components/Leaderboard.vue
> +const updateError = ref<string | null>(null)
You can simply make this a `ref<string>` and default to an empty string, which is still falsey.

2024-12-15 19:08 UTC, TheTedder commented on src/components/Leaderboard.vue
> +			<span v-if="updateError !== null" class="errorText">{{ updateError }}</span>
Change this to `v-if="updateError"` because empty string is falsey. Also consider using `<p>` instead.

2024-12-16 00:27 UTC, zysim commented on src/components/Leaderboard.vue
> +			updateError.value = 'Failed to delete: ' + (error as Response).status.toString(10)
Oh yeah I forget we have that

2024-12-16 01:06 UTC, TheTedder requested changes

2024-12-16 01:06 UTC, TheTedder commented on src/components/Leaderboard.vue
> +			>
I don't think this is meant to be here.

2024-12-16 06:49 UTC, zysim commented on src/components/Leaderboard.vue
> +			>
Yeah on second thought I'll drop it. Made sense to me at the time to have this link back to the list page even though there already is a link in the navbar.

2024-12-16 06:54 UTC, TheTedder commented on src/components/Leaderboard.vue
> +			>
No I mean I think it's literally in the wrong spot. It looked like it was in the error container.

2024-12-17 23:34 UTC, TheTedder requested changes

2024-12-17 23:34 UTC, TheTedder commented on src/components/Leaderboard.vue
> +			<p class="errorText">{{ error }}</p>
The error object isn't going to print nicely. It'll just give you some [object Object] type nonsense.

2024-12-17 23:37 UTC, TheTedder requested changes

2024-12-17 23:37 UTC, TheTedder commented on src/components/Leaderboard.vue
> +					'Failed to delete: ' + (error as Response).status.toString(10)
Unnecessary cast (one instance below as well)

2024-12-18 10:56 UTC, zysim commented on src/components/Leaderboard.vue
> +			<p class="errorText">{{ error }}</p>
You're right..

Changed the code to get the JSON from the error and print the status and title. Should look something like this now:
![image](https://github.com/user-attachments/assets/99502502-f855-4e09-a0a6-c1ec40ba44ac)

2025-01-04 21:02 UTC, TheTedder approved these changes

2025-01-04 21:02 UTC, merged